name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout code
      - name: Checkout out repository
        uses: actions/checkout@v4

      # 2) Setup JDK 21
      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3) Cache Maven dependencies (optional, but speeds up repeated builds)
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # 4) Build and run tests
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify


  publish-to-github-packages:
    if: github.ref == 'refs/heads/master'
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
            java-version: '21'
            distribution: 'temurin'
            server-id: github
            server-username: GITHUB_ACTOR
            server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Github Packages
        run: mvn --batch-mode deploy --settings ~/.m2/settings.xml